---
# tasks file for clickhouse
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_release | lower }}.yml"
    - "empty.yml"

- include: precheck.yml

- include: "{{ item }}"
  with_first_found:
    - "install_{{ ansible_pkg_mgr }}.yml"
    - "empty.yml"
  when: clickhouse_setup == 'package' and (clickhouse_rt_is_installed.rc !=0 or not clickhouse_is_required_version) and clickhouse_remove|bool == False

- include: config_sys.yml
  when: clickhouse_rt_is_installed.rc == 0 and clickhouse_remove|bool == False

- name: Wait DBMS ready
  command: sleep 1

- include: config_db.yml
  when: clickhouse_rt_is_installed.rc == 0 and clickhouse_remove|bool == False


# - include: config_dict.yml
#   when: clickhouse_rt_is_installed.rc == 0 and clickhouse_remove|bool == False
#   tags: [config,config_dict]

- include: "{{ item }}"
  with_first_found:
    - "remove_{{ ansible_pkg_mgr }}.yml"
    - "empty.yml"
  when: clickhouse_setup == 'package' and clickhouse_rt_is_installed.rc == 0 and clickhouse_remove|bool == True
